CREATE TABLE IF NOT EXISTS lawyers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  bar_number VARCHAR(50),
  specialization VARCHAR(100),
  years_of_experience INT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
); 